### ISSUE TITLE
Minimum PHP version option not working

### ISSUE THREAD

**Issue by vedathemes** [WPTRT/theme-sniffer#102] opened 2019-02-26 13:03 UTC
To re-produce this error, check latest version of my theme at https://themes.trac.wordpress.org/ticket/63695. Set minimum php version to 5.4 and run the plugin sniffer. It will still show all errors related to keywords or syntax available in PHP 5.4.

**Comment by dingo-d** [comment] 2019-02-26 14:46
I will try to test this using the plugin, but I didn't get any errors when manually running the PHPCompatibility sniff. Thanks for reporting this  :)

**Comment by joyously** [comment] 2019-02-26 15:58
Doesn't minimum PHP version mean that that is the version that is checked for? The description sounds correct. What are you saying the problem is?

**Comment by vedathemes** [comment] 2019-02-26 16:11
Description is correct. The problem is, if I have selected Minimum PHP version as 5.4 and run the sniffer, It should not show an error saying "Short array syntax (open) is available since 5.4".

**Comment by ernilambar** [comment] 2019-02-27 04:48
I can confirm this bug. Plugin is not respecting the PHP version dropdown.

**Comment by dingo-d** [comment] 2019-02-27 08:44
I'll test this with some more themes and see what's causing this. Must be some config issue

**Comment by dingo-d** [comment] 2019-03-01 12:55
I've updated the zip file, can you check for the issue now?

https://github.com/WPTRT/theme-sniffer/releases/download/1.0.0-RC1/theme-sniffer.zip

**Comment by dingo-d** [comment] 2019-03-04 11:02
This has been fixed and is in the current zip so I'll close the issue.

**Closed by dingo-d** 2019-03-04 11:02 UTC
Labels: bug, issue: has PR
